### ISSUE TITLE
Optimization: Support non-canonical representation for values

### ISSUE THREAD

**Issue by merryhime** [merryhime/dynarmic#56]
Note to self.

This would be beneficial when the canonical representation is inefficient due to a constant need to convert to and from that representation.

Examples of this include:

* GE Flags -> These could remain as expanded XMM masks until storage in CPSR is necessary.
* NZCV Flags -> These *could* be represented in a format such as `sahf` until conversion is necessary.
* In some parallel instructions especially in the implementation of saturated instructions supporting a [non-canonical expanded representation](https://github.com/MerryMage/dynarmic/blob/e166965f3e2a06761bd3421eb780e70cc1419dfd/src/backend_x64/emit_x64.cpp#L1279-L1282) can be helpful.

**Comment by MerryMage** [comment]
**Potential Interface Example:**

    enum class ValueRepr {
        Canonical,
        // Normally NZCV flags are stored as bits in individual GPR registers.
        // This format keeps them all in one byte.
        // Format: <todo>
        CompressedNZCV,
        // The GE Flags are normally four bits wide, like so: abcd
        // This representation expands them to fill 32 bits, like so:
        // aaaaaaaabbbbbbbbccccccccdddddddd
        ExpandedGEMask,
        // The GE Flags are normally four bits wide, like so: abcd
        // This representation expands them to fill 64 bits, like so:
        // aaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbccccccccccccccccdddddddddddddddd
        WideExpandedGEMask,
        // Canonical: aaaaaaaabbbbbbbbccccccccdddddddd
        // Non-canonical: 00000000aaaaaaaa00000000bbbbbbbb00000000cccccccc00000000dddddddd
        PackedU8ToWideU16,
    };

    Xbyak::Reg64 RegAlloc::UseGpr(IR::Value use_value, ValueRepr repr = ValueRepr::Canonical, HostLocList desired_locations = any_gpr)

**Comment by MerryMage** [comment]
Flag-based things are mostly done, and are tracked by #86.

**Comment by merryhime** [comment]
Superseeded by various current optimizations.
