### ISSUE TITLE
Possible to use Dynarmic as an interpreter only?

### ISSUE THREAD

**Issue by AeonLucid** [merryhime/dynarmic#642]
Hi,

Is it possible to use Dynarmic without the [Emission / Execution](https://github.com/merryhime/dynarmic/blob/master/docs/Design.md) steps?
So that all instructions are interpreted. If not possible, would it be difficult for me to make modifications so it is?

I know this won't be very fast but my usecase is to only interpret a very small amount of instructions on an ARM host (iOS / M1), which does also not allow JIT functionality. Which is why I am looking for an A64 interpreter.

_Wasn't sure where to ask this question since discussions are disabled and there was no mention of a discord server. If there is any, please let me know._

**Comment by AeonLucid** [comment]
I just found out that dynarmic does not even have an interpreter, so I guess I can close this.

**Comment by merryhime** [comment]
Unfortunately interpretation isn't an option currently, but would be a welcome addition.

**Comment by AeonLucid** [comment]
@merryhime Would you happen to know of any other project that could fit my needs? Even if I have to strip it.
