### ISSUE TITLE
How to emulate multi-threads?

### ISSUE THREAD

**Issue by avdbg** [merryhime/dynarmic#663]
I want to use dynarmic to emulate multiple threads to run some ARM code that access the same memory. I construct `A64::Jit` for every thread and that use the same `UserCallbacks`. Is there any problem with this? 
Thanks.

**Comment by merryhime** [comment]
As long as there is no per-thread state in your `UserCallbacks` object or any other state you need to synchronize, there shouldn't be any issue with this.

**Comment by avdbg** [comment]
Ok, thanks.

**Comment by FernandoS27** [comment]
> 

if you need help, you can feel free to write us in yuzu in discord. My account is Blinkhawk#2544
