### ISSUE TITLE
Can't compile from AUR: class template argument deduction failed

### ISSUE THREAD

**Issue by RiedleroD** [merryhime/dynarmic#683]
I tried to install `dynarmic-git` from the AUR. I have no idea what it means, but here's the log: https://pastebin.com/LrQTvp9R - I truncated the successful compilation messages before the error.

I updated my system before this and made sure this wasn't due to weird configs on my part. Still, I'm not entirely sure if it is my fault or not, since I'm seemingly the first person with this specific problem.

**Comment by merryhime** [comment]
Hey, thanks for the heads up! This is likely because the most recent update of xbyak changed how cpu information is stored (used to be a 64-bit limitation.)

I'll update our bundled copy of xbyak to the latest version, but in the meantime you can blank `x64_cpu_info.cpp` since that's just a test.

**Comment by merryhime** [comment]
Fixed in 11d12d0b84452b93e3b1efb46b3cec68cf5a970a.

**Comment by RiedleroD** [comment]
Thanks! You fixed this incredibly quickly, holy crap.
