### ISSUE TITLE
Please update fmt to 9.0.0

### ISSUE THREAD

**Issue by zhsj** [merryhime/dynarmic#699]
Hi,

fmt has released 9.0.0. Could you upgrade your version?

I have seen that dynarmic 6.0.0 failed to build with fmt 9.0.0 [1]. But I'm not sure if the master version works. So if you have updated the bundled fmt to 9.0.0 as well, it would be appreciated. 

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014674

**Comment by merryhime** [comment]
Closed in 6.2.2.

**Comment by zhsj** [comment]
thanks

**Comment by merryhime** [comment]
note: avoided deprecated API use in 6.2.3
