### ISSUE TITLE
Compilation failure: "cannot take address of consteval function 'GetMaskAndExpect' outside of an immediate invocation"

### ISSUE THREAD

**Issue by PureTryOut** [merryhime/dynarmic#708]
```
src/dynarmic/frontend/decoder/decoder_detail.h:175:43: error: cannot take address of consteval function 'GetMaskAndExpect' outside of an immediate invocation
        constexpr auto mask = std::get<0>(GetMaskAndExpect(bitstring));
                                          ^
src/dynarmic/frontend/decoder/decoder_detail.h:48:27: note: declared here
    static consteval auto GetMaskAndExpect(std::array<char, opcode_bitsize> bitstring) {
                          ^
src/dynarmic/frontend/decoder/decoder_detail.h:176:45: error: cannot take address of consteval function 'GetMaskAndExpect' outside of an immediate invocation
        constexpr auto expect = std::get<1>(GetMaskAndExpect(bitstring));
                                            ^
src/dynarmic/frontend/decoder/decoder_detail.h:48:27: note: declared here
    static consteval auto GetMaskAndExpect(std::array<char, opcode_bitsize> bitstring) {
                          ^
2 errors generated.
```

**Comment by merryhime** [comment]
Which compiler is affected?

**Comment by PureTryOut** [comment]
This is currently with Clang 14.0.6 and the Musl libc

**Comment by wheremyfoodat** [comment]
Reproduced this issue with both Clang 12.0.0 and Clang 14.0.6 on Windows

**Comment by merryhime** [comment]
Annoying. Not entirely sure where this issue is arising from; will change to `constexpr`.

**Comment by Macdu** [comment]
This looks like a bug in clang  ([https://github.com/dolphin-emu/dolphin/pull/10973](https://github.com/dolphin-emu/dolphin/pull/10973), although in this PR they said it was solved in clang 14.0).  I think it comes from the fact that calling a consteval function outside of an immediate invocation was added later in the specification(see [https://open-std.org/JTC1/SC22/WG21/docs/papers/2020/p1937r2.html](https://open-std.org/JTC1/SC22/WG21/docs/papers/2020/p1937r2.html)).

**Comment by merryhime** [comment]
Thanks @Macdu. Potential workaround pushed 075047fbf.

**Comment by nekopsykose** [comment]
workaround works fine with the same initial configuration
