### ISSUE TITLE
build system: prefer "system" mcl

### ISSUE THREAD

**Issue by florhizome** [merryhime/dynarmic#733]
Hi, 
I am trying to package two projects using dynarmic (citra and yuzu) for GNU guix. 
In this effort,  I have asked citra to generally prefer using "system" dependencies (packages that are included in the build environment) [] over the bundled externals since this is a bad practice considered by many distributions  [here](https://github.com/citra-emu/citra/issues/6204). 
Luckily dynarmic already does that, with exception for "mcl" (although I would prefer `-DYNARMIC_USE_EXTERNALS=OFF` as default). WIth one exception: there are functional differences between using a git submodule and copying a static checkout into the project, we still prefer to provide dependencys ourself.
Could you adapt your build system accordingly, please? :) 
cheers!

**Comment by merryhime** [comment]
This is acceptable? 83714656904646a1d3708235764d5d4765b4c133
