### ISSUE TITLE
Cannot compile dynarmic (AUR)

### ISSUE THREAD

**Issue by CyberYoshi64** [merryhime/dynarmic#747]
This compilation failure occured ever since 6.4.1
```
[ 88%] Linking CXX shared library libdynarmic.so
/usr/bin/ld: /usr/lib/libfmt.a(format.cc.o): warning: relocation against `_ZTIN3fmt2v912format_errorE' in read-only section `.text._ZN3fmt2v96detail12format_floatIdEEiT_iNS1_11float_specsERNS1_6bufferIcEE[_ZN3fmt2v96detail12format_floatIdEEiT_iNS1_11float_specsERNS1_6bufferIcEE]'
/usr/bin/ld: /usr/lib/libfmt.a(format.cc.o): relocation R_X86_64_PC32 against symbol `_ZTVN3fmt2v912format_errorE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[2]: *** [src/dynarmic/CMakeFiles/dynarmic.dir/build.make:3110: src/dynarmic/libdynarmic.so.6.4.5] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1033: src/dynarmic/CMakeFiles/dynarmic.dir/all] Fehler 2
make: *** [Makefile:146: all] Fehler 2
```
I even tried manually compiling it but this issue won't resolve by itself.

**Comment by merryhime** [comment]
@abouvier

**Comment by merryhime** [comment]
Do you have fmt installed? For some reason, you're linking against a static library rather than a shared object.

**Comment by abouvier** [comment]
There is not enough information. What command did you use to compile the package? What is the result of `$ pacman -Qo /usr/lib/libfmt.a`?

**Comment by CyberYoshi64** [comment]
> There is not enough information. What command did you use to compile the package? What is the result of `$ pacman -Qo /usr/lib/libfmt.a`?

I simply used AUR through `yay -S dynarmic`
pacman's output for the specified line you gave is:
`/usr/lib/libfmt.a ist in citra-qt-git r9391.9c6035f25-1 enthalten`

Although as I mentioned, it did compile and install fine pre-6.4.1
