### ISSUE TITLE
question

### ISSUE THREAD

**Issue by CodeNinja-sys** [merryhime/dynarmic#755]
I think I'm writing in the wrong place, but okay

I have a question, can I use dynamic in my IOS 2/3 emulator?

(I get a error when I write to you on twitter)

**Comment by FearlessTobi** [comment]
Legally, you can use this emulator as long as you comply with the BSD 0-Clause license, which should be very easy.

**Comment by CodeNinja-sys** [comment]
> Legally, you can use this emulator as long as you comply with the BSD 0-Clause license, which should be very easy.

ok, thank you

**Comment by merryhime** [comment]
Take a look at https://github.com/merryhime/dynarmic#legal for the licenses for all associated software packages.
